apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: inno
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: inno
type: Opaque
stringData:
  JWT_SECRET: eyJhbGciOiJIUzM4NCJ9eyJzdWIiOiIyIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODU2OTM4NDMsImV4cCI6MTc4NTY5NDc0M30