apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
  namespace: inno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: mongo
          image: mongo:7
          command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: paymentdb
          volumeMounts:
            - name: data
              mountPath: /data/db
          readinessProbe:
            exec:
              command: ["mongosh", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 60 #10
            periodSeconds: 5
            timeoutSeconds: 10 #5
            failureThreshold: 6 #3
          livenessProbe:
            exec:
              command: ["mongosh", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 60 #15
            periodSeconds: 10
            timeoutSeconds: 10 #5
            failureThreshold: 6 #3
          resources:
            requests:
              cpu: 100m
              memory: 512Mi #256Mi
            limits:
              cpu: 800m #500m
              memory: 1Gi #512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: payment-db-pvc