apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-redis
  namespace: inno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-redis
  template:
    metadata:
      labels:
        app: order-redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi